# Generated by Django 6.0.2 on 2026-07-17 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('products', '0002_combo_comboitem_combomealsuggestion'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing Orders'), ('optimizing', 'Optimizing Prices'), ('assigning', 'Assigning Vendors'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total savings achieved through aggregation', max_digits=12)),
                ('average_savings_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Average percentage saved per order', max_digits=5)),
                ('vendors_involved', models.IntegerField(default=0)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregation_runs', to='clusters.cluster')),
            ],
            options={
                'db_table': 'aggregation_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('selected_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('market_average_price', models.DecimalField(decimal_places=2, help_text='Average market price for comparison', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('savings_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('alternatives_evaluated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_optimizations', to='aggregation.aggregationrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_optimizations', to='products.product')),
                ('selected_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_wins', to='vendors.vendor')),
            ],
            options={
                'db_table': 'price_optimizations',
                'ordering': ['-total_savings'],
            },
        ),
        migrations.CreateModel(
            name='VendorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('partial', 'Partially Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_allocations', to='aggregation.aggregationrun')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_allocations',
                'ordering': ['-total_value'],
            },
        ),
        migrations.AddIndex(
            model_name='aggregationrun',
            index=models.Index(fields=['cluster', 'status'], name='aggregation_cluster_bd59c7_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregationrun',
            index=models.Index(fields=['-started_at'], name='aggregation_started_8cbb54_idx'),
        ),
        migrations.AddIndex(
            model_name='priceoptimization',
            index=models.Index(fields=['aggregation_run', 'product'], name='price_optim_aggrega_80f0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='priceoptimization',
            index=models.Index(fields=['selected_vendor'], name='price_optim_selecte_22bd20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='priceoptimization',
            unique_together={('aggregation_run', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorallocation',
            unique_together={('aggregation_run', 'vendor')},
        ),
    ]
