# Generated by Django 6.0.2 on 2026-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Confirmed cluster quantity required to unlock this tier', unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage off the base price, e.g. 15.00 for 15%', max_digits=5)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Bulk Saver'", max_length=100)),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'db_table': 'pricing_tiers',
                'ordering': ['min_quantity'],
            },
        ),
    ]
