# Generated by Django 6.0.2 on 2026-03-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('FARMER', 'Farmer'), ('WHOLESALER', 'Wholesaler'), ('MARKET', 'Market Vendor'), ('COOPERATIVE', 'Cooperative')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('trust_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['-trust_score', 'name'],
                'indexes': [models.Index(fields=['name'], name='vendors_name_a8eecc_idx'), models.Index(fields=['trust_score'], name='vendors_trust_s_a1ba1c_idx'), models.Index(fields=['is_active'], name='vendors_is_acti_04b085_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_prices', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Price',
                'verbose_name_plural': 'Vendor Prices',
                'db_table': 'vendor_prices',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['vendor', 'product'], name='vendor_pric_vendor__9eae05_idx'), models.Index(fields=['price'], name='vendor_pric_price_05627c_idx'), models.Index(fields=['is_available'], name='vendor_pric_is_avai_425a13_idx')],
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
