# Generated by Django 6.0.2 on 2026-06-04 02:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggDeliveryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('crates', models.PositiveIntegerField()),
                ('price_per_crate', models.DecimalField(decimal_places=2, default=Decimal('5650.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_bookings', to='clusters.cluster')),
            ],
            options={
                'verbose_name': 'Egg Delivery Booking',
                'verbose_name_plural': 'Egg Delivery Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
