# Generated by Django 6.0.2 on 2026-05-20 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0002_combo_comboitem_combomealsuggestion'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_created_77e2b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_order_i_26ad88_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_product_a53db1_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_vendor__07b5fe_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Payment Pending'), ('SUCCESS', 'Paid'), ('FAILED', 'Payment Failed')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.combo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_reference'], name='orders_payment_5a5a3d_idx'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
    ]
