# Generated by Django 6.0.2 on 2026-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PILOT', 'Pilot')], default='PILOT', max_length=20)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'db_table': 'clusters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clusters_name_cd49f9_idx'), models.Index(fields=['status'], name='clusters_status_2400a6_idx')],
            },
        ),
    ]
