# Generated by Django 6.0.2 on 2026-05-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short tagline for the combo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeds', models.CharField(help_text="e.g., '1 person', '4 people'", max_length=100)),
                ('duration', models.CharField(help_text="e.g., '2 weeks', '1 month'", max_length=100)),
                ('meals_count', models.IntegerField(help_text='Approximate number of meals')),
                ('use_case', models.CharField(choices=[('students', 'Students'), ('families', 'Families'), ('shared', 'Shared/Hostel'), ('events', 'Events')], default='students', max_length=20)),
                ('badge', models.CharField(blank=True, choices=[('popular', 'Most Popular'), ('value', 'Best Value'), ('premium', 'Premium'), ('new', 'New'), ('limited', 'Limited Time')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on featured combos section')),
                ('featured_order', models.IntegerField(default=0, help_text='Order in featured section (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Combo',
                'verbose_name_plural': 'Food Combos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_text', models.CharField(help_text="e.g., '5 cups', 'half pint', '1 pack', '2 sachets'", max_length=100)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for calculations (optional)', max_digits=10, null=True)),
                ('quantity_unit', models.CharField(blank=True, help_text='Unit: cups, kg, packs, liters, etc.', max_length=50)),
                ('notes', models.CharField(blank=True, help_text="e.g., 'for breakfast', 'for rice & stew'", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order in combo')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Combo Item',
                'verbose_name_plural': 'Combo Items',
                'ordering': ['order', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ComboMealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(help_text="e.g., 'Jollof Rice', 'Beans Porridge'", max_length=200)),
                ('frequency', models.CharField(help_text="e.g., '4-5 times', '10+ servings'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_suggestions', to='products.combo')),
            ],
            options={
                'verbose_name': 'Meal Suggestion',
                'verbose_name_plural': 'Meal Suggestions',
                'ordering': ['order'],
            },
        ),
    ]
