# Generated by Django 5.0.14 on 2026-07-23 09:58

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_combo_comboitem_combomealsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', validators=[config.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[config.validators.validate_image_size]),
        ),
    ]
