# Generated by Django 6.0.2 on 2026-07-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occasion', models.CharField(choices=[('FAMILY', 'Family Meal'), ('PARTY', 'Birthday / Party'), ('RESTAURANT', 'Restaurant Menu'), ('OTHER', 'Custom')], max_length=20)),
                ('people_count', models.PositiveIntegerField()),
                ('budget_naira', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dietary_notes', models.TextField(blank=True)),
                ('ai_response', models.JSONField(help_text='Full structured plan returned by the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Request',
                'verbose_name_plural': 'Plan Requests',
                'db_table': 'plan_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
